### ISSUE TITLE
Sometimes, search is wrong

### ISSUE THREAD

**Issue by sujaypawar** [Nikschavan/customizer-search#15]
Try searching Facebook on Astra Theme:
http://screenshots.sharkz.in/sujay/180303172737.png

**Comment by Nikschavan** [comment]
Right now the search looks for minimum matched characters. in the screenshot the results are matched for the characters `fa`. I think we can highlight the matched characters so that it's more clear  what the search results are for.

**Comment by Nikschavan** [comment]
This is how the actual search results is matched in this particular case - [screenshot](https://cl.ly/pvXy)
